spring.application.name=casildamart
spring.datasource.url=jdbc:mysql://localhost:3306/casildamart
spring.datasource.username=root
spring.datasource.password=casilda@2007

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

spring.thymeleaf.cache=false